from pathlib import Path


SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 30

CAMERA_INDEX = 0

FACE_MISSING_FAIL_SECONDS = 2.0
FACE_TRACK_INTERVAL_SECONDS = 0.1
FACE_LANDMARKER_MODEL_PATH = "assets/models/face_landmarker.task"

AUDIO_LIMIT_DB = 65.0

YOLO_MODEL_NAME = "assets/models/yolov8n.pt"
YOLO_DETECT_EVERY_N_FRAMES = 5

WHISPER_MODEL_NAME = "tiny"
WHISPER_MODEL_DIR = "assets/models"
SPEECH_TARGET_TEXT = "붉은 문을 열어라"
SPEECH_SIMILARITY_PASS = 0.75

STAGE1_DURATION_SECONDS = 10.0
STAGE2_TIME_LIMIT_SECONDS = 20.0
STAGE3_TIME_LIMIT_SECONDS = 30.0
STAGE_TRANSITION_SECONDS = 5.0

FONT_PATH = Path("assets/fonts/MUNMAK_DALBANCHE.ttf")
